
//Listas

const tipoDocumento = [
    { value: "1", text: "Documento Nacional de Identidad" },
    { value: "2", text: "Otro." },
];

//Después va a una base de datos
const listaProvincias = [
    { value: "1", text: "Buenos Aires" },
    { value: "2", text: "Capital Federal" },
    { value: "3", text: "Catamarca" },
    { value: "4", text: "Córdoba" },
    { value: "5", text: "Corrientes" },
    { value: "6", text: "Chaco" },
    { value: "7", text: "Chubut" },
    { value: "8", text: "Entre Ríos" },
    { value: "9", text: "Formosa" },
    { value: "10", text: "Jujuy" },
    { value: "11", text: "La Pampa" },
    { value: "12", text: "La Rioja" },
    { value: "13", text: "Mendoza" },
    { value: "14", text: "Misiones" },
    { value: "15", text: "Neuquén" },
    { value: "16", text: "Río Negro" },
    { value: "17", text: "Salta" },
    { value: "18", text: "San Juan" },
    { value: "19", text: "San Luis" },
    { value: "20", text: "Santa Cruz" },
    { value: "21", text: "Santa Fe" },
    { value: "22", text: "Santiago del Estero" },
    { value: "23", text: "Tierra del Fuego" },
    { value: "24", text: "Tucumán" },
];


// Después va a una base de datos.
const listaPaises=[
{value:"1",text:"Afganistán"},
{value:"2",text:"Albania"},
{value:"3",text:"Alemania"},
{value:"4",text:"Andorra"},
{value:"5",text:"Angola"},
{value:"6",text:"Antigua y Barbuda"},
{value:"7",text:"Arabia Saudita"},
{value:"8",text:"Argelia"},
{value:"9",text:"Argentina"},
{value:"10",text:"Armenia"},
{value:"11",text:"Australia"},
{value:"12",text:"Austria"},
{value:"13",text:"Azerbaiyán"},
{value:"14",text:"Bahamas"},
{value:"15",text:"Bangladés"},
{value:"16",text:"Barbados"},
{value:"17",text:"Baréin"},
{value:"18",text:"Bélgica"},
{value:"19",text:"Belice"},
{value:"20",text:"Benjn"},
{value:"21",text:"Bielorrusia"},
{value:"22",text:"Birmania"},
{value:"23",text:"Bolivia"},
{value:"24",text:"Bosnia-Herzegovina"},
{value:"25",text:"Botsuana"},
{value:"26",text:"Brasil"},
{value:"27",text:"Brunéi"},
{value:"28",text:"Bulgaria"},
{value:"29",text:"Burkina Faso"},
{value:"30",text:"Burundi"},
{value:"31",text:"Bután"},
{value:"32",text:"Cabo Verde"},
{value:"33",text:"Camboya"},
{value:"34",text:"Camerún"},
{value:"35",text:"Canadá"},
{value:"36",text:"Catar"},
{value:"37",text:"Chad"},
{value:"38",text:"Chile"},
{value:"39",text:"China"},
{value:"40",text:"Chipre"},
{value:"41",text:"Colombia"},
{value:"42",text:"Comoras"},
{value:"43",text:"Congo"},
{value:"44",text:"Corea del Norte"},
{value:"45",text:"Corea del Sur"},
{value:"46",text:"Costa de Marfil"},
{value:"47",text:"Costa Rica"},
{value:"48",text:"Croacia"},
{value:"49",text:"Cuba"},
{value:"50",text:"Dinamarca"},
{value:"51",text:"Dominica"},
{value:"52",text:"Ecuador"},
{value:"53",text:"Egipto"},
{value:"54",text:"El Salvador"},
{value:"55",text:"Emiratos Arabes Unidos"},
{value:"56",text:"Eritrea"},
{value:"57",text:"Eslovaquia"},
{value:"58",text:"Eslovenia"},
{value:"59",text:"España"},
{value:"60",text:"Estados Unidos"},
{value:"61",text:"Estonia"},
{value:"62",text:"Esuatini"},
{value:"63",text:"Etiopía"},
{value:"64",text:"Filipinas"},
{value:"65",text:"Finlandia"},
{value:"66",text:"Fiyi"},
{value:"67",text:"Francia"},
{value:"68",text:"Gabón"},
{value:"69",text:"Gambia"},
{value:"70",text:"Georgia"},
{value:"71",text:"Ghana"},
{value:"72",text:"Granada"},
{value:"73",text:"Grecia"},
{value:"74",text:"Guatemala"},
{value:"75",text:"Guinea"},
{value:"76",text:"Guinea Ecuatorial"},
{value:"77",text:"Guinea-Bisáu"},
{value:"78",text:"Guyana"},
{value:"79",text:"Haití"},
{value:"80",text:"Honduras"},
{value:"81",text:"Hungr¡a"},
{value:"82",text:"India"},
{value:"83",text:"Indonesia"},
{value:"84",text:"Irak"},
{value:"85",text:"Irán"},
{value:"86",text:"Irlanda"},
{value:"87",text:"Islandia"},
{value:"88",text:"Islas Marshall"},
{value:"89",text:"Islas Salomón"},
{value:"90",text:"Israel"},
{value:"91",text:"Italia"},
{value:"92",text:"Jamaica"},
{value:"93",text:"Japón"},
{value:"94",text:"Jordania"},
{value:"95",text:"Kazajistán"},
{value:"96",text:"Kenia"},
{value:"97",text:"Kirguistán"},
{value:"98",text:"Kiribati"},
{value:"99",text:"Kosovo"},
{value:"100",text:"Kuwait"},
{value:"101",text:"Laos"},
{value:"102",text:"Lesoto"},
{value:"103",text:"Letonia"},
{value:"104",text:"L¡bano"},
{value:"105",text:"Liberia"},
{value:"106",text:"Libia"},
{value:"107",text:"Liechtenstein"},
{value:"108",text:"Lituania"},
{value:"109",text:"Luxemburgo"},
{value:"110",text:"Macedonia del Norte"},
{value:"111",text:"Madagascar"},
{value:"112",text:"Malasia"},
{value:"113",text:"Malaui"},
{value:"114",text:"Maldivas"},
{value:"115",text:"Malí"},
{value:"116",text:"Malta"},
{value:"117",text:"Marruecos"},
{value:"118",text:"Mauricio"},
{value:"119",text:"Mauritania"},
{value:"120",text:"México"},
{value:"121",text:"Micronesia"},
{value:"122",text:"Moldavia"},
{value:"123",text:"Mónaco"},
{value:"124",text:"Mongolia"},
{value:"125",text:"Montenegro"},
{value:"126",text:"Mozambique"},
{value:"127",text:"Namibia"},
{value:"128",text:"Nauru"},
{value:"129",text:"Nepal"},
{value:"130",text:"Nicaragua"},
{value:"131",text:"Níger"},
{value:"132",text:"Nigeria"},
{value:"133",text:"Noruega"},
{value:"134",text:"Nueva Zelanda"},
{value:"135",text:"Omán"},
{value:"136",text:"Pa¡ses Bajos"},
{value:"137",text:"Pakistán"},
{value:"138",text:"Palaos"},
{value:"139",text:"Palestina"},
{value:"140",text:"Panamá"},
{value:"141",text:"Papúa Nueva Guinea"},
{value:"142",text:"Paraguay"},
{value:"143",text:"Perú"},
{value:"144",text:"Polonia"},
{value:"145",text:"Portugal"},
{value:"146",text:"Reino Unido"},
{value:"147",text:"Repéblica Centroafricana"},
{value:"148",text:"Repéblica Checa"},
{value:"149",text:"Repéblica Democrática del Congo"},
{value:"150",text:"Repéblica Dominicana"},
{value:"151",text:"Ruanda"},
{value:"152",text:"Rumania"},
{value:"153",text:"Rusia"},
{value:"154",text:"Samoa"},
{value:"155",text:"San Crist¢bal y Nieves"},
{value:"156",text:"San Marino"},
{value:"157",text:"San Vicente y las Granadinas"},
{value:"158",text:"Santa Luc¡a"},
{value:"159",text:"Santo Tomé y Pr¡ncipe"},
{value:"160",text:"Senegal"},
{value:"161",text:"Serbia"},
{value:"162",text:"Seychelles"},
{value:"163",text:"Sierra Leona"},
{value:"164",text:"Singapur"},
{value:"165",text:"Siria"},
{value:"166",text:"Somalia"},
{value:"167",text:"Sri Lanka"},
{value:"168",text:"Sudáfrica"},
{value:"169",text:"Sudán"},
{value:"170",text:"Sudán del Sur"},
{value:"171",text:"Suecia"},
{value:"172",text:"Suiza"},
{value:"173",text:"Surinam"},
{value:"174",text:"Tailandia"},
{value:"175",text:"Taiwán"},
{value:"176",text:"Tanzania"},
{value:"177",text:"Tayikistán"},
{value:"178",text:"Timor Oriental"},
{value:"179",text:"Togo"},
{value:"180",text:"Tonga"},
{value:"181",text:"Trinidad y Tobago"},
{value:"182",text:"Túnez"},
{value:"183",text:"Turkmenistán"},
{value:"184",text:"Turqu¡a"},
{value:"185",text:"Tuvalu"},
{value:"186",text:"Ucrania"},
{value:"187",text:"Uganda"},
{value:"188",text:"Uruguay"},
{value:"189",text:"Uzbekistán"},
{value:"190",text:"Vanuatu"},
{value:"191",text:"Vaticano"},
{value:"192",text:"Venezuela"},
{value:"193",text:"Vietnam"},
{value:"194",text:"Yemen"},
{value:"195",text:"Yibuti"},
{value:"196",text:"Zambia"},
{value:"197",text:"Zimbabue"},
];
